import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import React from "react";
import SessionWrapperProvider from "./provider";

import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "Airtable",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/airtable-tab-icon.svg" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable} h-full`}>
      <body className="w-full min-h-screen">
        <SessionWrapperProvider>{children}</SessionWrapperProvider>
      </body>
    </html>
  );
}
